method = "GET" 
retry_times = 3 
timeout = 300 # second

[strategy.eth]
type = "linear"
[[stragety.eth.primitive]]
primitive_type = "whitelist"
weight = 0.1
[[stragety.eth.primitive]]
primitive_type = "bytecode"
weight = 0.1

[strategy.bsc]
type = "linear"
[[stragety.bsc.primitive]]
primitive_type = "sourcecode"
weight = 0.1
[[stragety.bsc.primitive]]
primitive_type = "blacklist"
weight = 0.1
